Adjust placeholder project name to stand out more; Implement cli health check

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -4,19 +4,19 @@ SHELL ["/bin/bash", "-c"]
 WORKDIR /app
 
 # Build Args
-ARG PROJECTNAME_DEPLOYMENT_ENVIRONMENT
-ARG PROJECTNAME_GLOBAL_CONFIG_DIR
-ARG PROJECTNAME_MODEL_CONFIG_DIR
+ARG FOO_PROJECT_NAME_DEPLOYMENT_ENVIRONMENT
+ARG FOO_PROJECT_NAME_GLOBAL_CONFIG_DIR
+ARG FOO_PROJECT_NAME_MODEL_CONFIG_DIR
 
 # Validate Build Args that don't have a default
-RUN [[ -n "$PROJECTNAME_DEPLOYMENT_ENVIRONMENT" ]] || { echo "ERROR: PROJECTNAME_DEPLOYMENT_ENVIRONMENT build arg is required" && exit 1; }
-RUN [[ -n "$PROJECTNAME_GLOBAL_CONFIG_DIR" ]] || { echo "ERROR: PROJECTNAME_GLOBAL_CONFIG_DIR build arg is required" && exit 1; }
-RUN [[ -n "$PROJECTNAME_MODEL_CONFIG_DIR" ]] || { echo "ERROR: PROJECTNAME_MODEL_CONFIG_DIR build arg is required" && exit 1; }
+RUN [[ -n "$FOO_PROJECT_NAME_DEPLOYMENT_ENVIRONMENT" ]] || { echo "ERROR: FOO_PROJECT_NAME_DEPLOYMENT_ENVIRONMENT build arg is required" && exit 1; }
+RUN [[ -n "$FOO_PROJECT_NAME_GLOBAL_CONFIG_DIR" ]] || { echo "ERROR: FOO_PROJECT_NAME_GLOBAL_CONFIG_DIR build arg is required" && exit 1; }
+RUN [[ -n "$FOO_PROJECT_NAME_MODEL_CONFIG_DIR" ]] || { echo "ERROR: FOO_PROJECT_NAME_MODEL_CONFIG_DIR build arg is required" && exit 1; }
 
 # Export Build Args
-ENV PROJECTNAME_DEPLOYMENT_ENVIRONMENT="$PROJECTNAME_DEPLOYMENT_ENVIRONMENT"
-ENV PROJECTNAME_GLOBAL_CONFIG_DIR="$PROJECTNAME_GLOBAL_CONFIG_DIR"
-ENV PROJECTNAME_MODEL_CONFIG_DIR="$PROJECTNAME_MODEL_CONFIG_DIR"
+ENV FOO_PROJECT_NAME_DEPLOYMENT_ENVIRONMENT="$FOO_PROJECT_NAME_DEPLOYMENT_ENVIRONMENT"
+ENV FOO_PROJECT_NAME_GLOBAL_CONFIG_DIR="$FOO_PROJECT_NAME_GLOBAL_CONFIG_DIR"
+ENV FOO_PROJECT_NAME_MODEL_CONFIG_DIR="$FOO_PROJECT_NAME_MODEL_CONFIG_DIR"
 
 COPY "." "/app/"
 
@@ -40,6 +40,6 @@ RUN ln -sf /usr/bin/python3.11 /usr/bin/python3 &&\
   ln -sf /usr/bin/python3.11 /usr/bin/python && \
   ln -sf /usr/bin/pip3.11 /usr/bin/pip
 
-RUN ./install.sh ${PROJECTNAME_DEPLOYMENT_ENVIRONMENT}
+RUN ./install.sh ${FOO_PROJECT_NAME_DEPLOYMENT_ENVIRONMENT}
 
 ENTRYPOINT ["./start-server.sh"]
